### ISSUE TITLE
HTTP 404 when a user trying to log in to an application is unknown to SBS

### ISSUE THREAD

**Issue by hcvdwerf** [SURFscz/SBS#1652] opened 2024-10-24 09:24 UTC
When a user who is not affiliated with any CO (Collaborative Organization) tries to login in the system(User portal), they are met with a 404 error page: 

![image](https://github.com/user-attachments/assets/5d9beaa3-17d7-4656-948b-6131fb1a478d)

This issue is a think related to https://github.com/SURFscz/SBS/issues/1500

**Comment by baszoetekouw** [comment] 2024-10-24 14:02
@oharsta This seems to be a regression of #1500.  Could you take a look?

**Comment by FlorisFokkinga** [comment] 2024-10-28 10:45
I've asked the user for more details.

**Comment by hcvdwerf** [comment] 2024-10-28 11:00
shared info via teams with @FlorisFokkinga

**Comment by FlorisFokkinga** [comment] 2024-10-28 13:30
## Reproduction
1. Start with an IdP account (e.g., eduID.nl) that has never logged in to SBS
2. Try to log in to an application connected to SRAM (without logging in to SBS or eduTEAMS first)

Expected: An SBS page explaining the users is not a member of a collaboration [1]
Observed: Said page redirects to the 404 page immediately

[1] E.g., https://sram.surf.nl/service-denied?service_name=Wordpress+demo&error_status=1&entity_id=APP-B968C3D6-D868-45C5-93D1-6AA2C8A90BF7&issuer_id=https%3A%2F%2Flogin.eduid.nl&user_id=a95ea4458d488734de0eb3e31942a0672cb2d662%40sram.surf.nl

**Comment by oharsta** [comment] 2024-10-28 14:38
Fixed in the new login-flow. Pending the decision of we want to make a bug-fix release for this or wait a regular production release.

**Closed by oharsta** 2024-10-28 14:38 UTC
Labels: bug

**Comment by mrvanes** [comment] 2024-10-28 15:02
No 404, but instead this screen from eduTeams
![Image](https://github.com/user-attachments/assets/8d0f5187-86e0-48a5-b424-01ea1d107824)

**Comment by mrvanes** [comment] 2024-11-04 12:45
When eduTeams cooperates (now and then), this issue is fixed on our side
