### ISSUE TITLE
Authz endpoint should always interrupt, mfa depend only on session timeout

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#1668] opened 2024-11-04 08:13 UTC
Based on the findings in #672 we decided that MFA timeout does not add any significant functionality to the flow and unnecessarily complicates the code, so:

1. MFA session timeout can be _removed_
2. Interrupt should _always_ be triggered and
3. MFA/TOTP should only depend on _session timeout_.

**Comment by mrvanes** [comment] 2024-11-05 09:03
I end up in a black hole again:
```
Nov 05 08:58:24 app1-tf1 gunicorn[1110489]: DEBUG [user_api] user: eduteams, proxy_authz called with {'user_id': 'd5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org', 'user_email': 'frodo@example.com', 'service_id': 'APP-18DE6298-7BDD-4CFA-9399-E1CC62E8DE05', 'issuer_id': 'http://mock-idp', 'uid': 'frodo', 'homeorganization': 'example.com'}
Nov 05 08:58:24 app1-tf1 gunicorn[1110489]: DEBUG [user_api] user: eduteams, mfa_idp_allowed: False (entity_id_allowed=[], schac_home_allowed=[], entity_id=http://mock-idp, schac_home=example.com
Nov 05 08:58:24 app1-tf1 gunicorn[1110489]: DEBUG [user_api] user: eduteams, Returning interrupt for user d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org from issuer http://mock-idp to perform 2fa
Nov 05 08:58:24 app1-tf1 gunicorn[1110489]: INFO  [base] user: eduteams, Path /api/users/proxy_authz POST {"user_id": "d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org", "user_email": "frodo@example.com", "service_id": "APP-18DE6298-7BDD-4CFA-9399-E1CC62E8DE05", "issuer_id": "http://mock-idp", "uid": "frodo", "homeorganization": "example.com"}
Nov 05 08:58:27 app1-tf1 gunicorn[1110491]: DEBUG [user_api] user: eduteams, proxy_authz called with {'user_id': 'd5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org', 'user_email': 'frodo@example.com', 'service_id': 'APP-B799ADC6-EA57-4383-B493-27FB03D9195F', 'issuer_id': 'http://mock-idp', 'uid': 'frodo', 'homeorganization': 'example.com'}
Nov 05 08:58:27 app1-tf1 gunicorn[1110491]: DEBUG [user_api] user: eduteams, Return authorized to start SBS login flow, service_entity_id=app-b799adc6-ea57-4383-b493-27fb03d9195f
Nov 05 08:58:27 app1-tf1 gunicorn[1110491]: INFO  [base] user: eduteams, Path /api/users/proxy_authz POST {"user_id": "d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org", "user_email": "frodo@example.com", "service_id": "APP-B799ADC6-EA57-4383-B493-27FB03D9195F", "issuer_id": "http://mock-idp", "uid": "frodo", "homeorganization": "example.com"}
Nov 05 08:58:27 app1-tf1 gunicorn[1110489]: DEBUG [resume-session/user] user: ext_api, Userinfo endpoint results {'name': 'Frodo Doe', 'given_name': 'Frodo', 'family_name': 'Doe', 'eduperson_scoped_affiliation': ['member@acc.sram.eduteams.org'], 'email': 'frodo@example.com', 'uid': ['frodo'], 'voperson_external_id': ['frodo@example.com'], 'eduperson_entitlement': ['urn:geant:eduteams.org:acc.sram.eduteams.org:group:surf-ram#acc.sram.eduteams.org'], 'sub': 'd5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org', 'voperson_id': ['d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org']}
Nov 05 08:58:27 app1-tf1 gunicorn[1110489]: INFO  [resume-session/user] user: ext_api, Updating user d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org with new claims / updated at
Nov 05 08:58:27 app1-tf1 gunicorn[1110489]: DEBUG [user_api] user: ext_api, mfa_idp_allowed: False (entity_id_allowed=[], schac_home_allowed=[], entity_id=https://proxy.acc.sram.eduteams.org, schac_home=example.com
Nov 05 08:58:27 app1-tf1 gunicorn[1110489]: DEBUG [resume-session/user] user: ext_api, SBS login for user d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org MFA check is required: True
Nov 05 08:58:27 app1-tf1 gunicorn[1110489]: DEBUG [redirect] user: ext_api, Redirecting user d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org to https://test.sram.surf.nl/2fa
Nov 05 08:58:41 app1-tf1 gunicorn[1110489]: INFO  [base] user: d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org, Path /api/mfa/verify2fa POST {"totp": "767531"}
Nov 05 08:58:42 app1-tf1 gunicorn[1110488]: DEBUG:user_api:user: eduteams, proxy_authz called with {'user_id': 'd5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org', 'user_email': 'frodo@example.com', 'service_id': 'APP-18DE6298-7BDD-4CFA-9399-E1CC62E8DE05', 'issuer_id': 'http://mock-idp', 'uid': 'frodo', 'homeorganization': 'example.com'}
Nov 05 08:58:42 app1-tf1 gunicorn[1110488]: DEBUG:user_api:user: eduteams, mfa_idp_allowed: False (entity_id_allowed=[], schac_home_allowed=[], entity_id=http://mock-idp, schac_home=example.com
Nov 05 08:58:42 app1-tf1 gunicorn[1110488]: DEBUG:user_api:user: eduteams, Returning interrupt for user d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org from issuer http://mock-idp to perform 2fa
Nov 05 08:58:42 app1-tf1 gunicorn[1110488]: INFO:base:user: eduteams, Path /api/users/proxy_authz POST {"user_id": "d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org", "user_email": "frodo@example.com", "service_id": "APP-18DE6298-7BDD-4CFA-9399-E1CC62E8DE05", "issuer_id": "http://mock-idp", "uid": "frodo", "homeorganization": "example.com"}
Nov 05 08:58:44 app1-tf1 gunicorn[1110488]: DEBUG:user_api:user: eduteams, proxy_authz called with {'user_id': 'd5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org', 'user_email': 'frodo@example.com', 'service_id': 'APP-18DE6298-7BDD-4CFA-9399-E1CC62E8DE05', 'issuer_id': 'http://mock-idp', 'uid': 'frodo', 'homeorganization': 'example.com'}
Nov 05 08:58:44 app1-tf1 gunicorn[1110488]: DEBUG:user_api:user: eduteams, mfa_idp_allowed: False (entity_id_allowed=[], schac_home_allowed=[], entity_id=http://mock-idp, schac_home=example.com
Nov 05 08:58:44 app1-tf1 gunicorn[1110488]: DEBUG:user_api:user: eduteams, Returning interrupt for user d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org from issuer http://mock-idp to perform 2fa
Nov 05 08:58:44 app1-tf1 gunicorn[1110488]: INFO:base:user: eduteams, Path /api/users/proxy_authz POST {"user_id": "d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org", "user_email": "frodo@example.com", "service_id": "APP-18DE6298-7BDD-4CFA-9399-E1CC62E8DE05", "issuer_id": "http://mock-idp", "uid": "frodo", "homeorganization": "example.com"}
Nov 05 08:58:47 app1-tf1 gunicorn[1110490]: DEBUG:user_api:user: eduteams, proxy_authz called with {'user_id': 'd5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org', 'user_email': 'frodo@example.com', 'service_id': 'APP-18DE6298-7BDD-4CFA-9399-E1CC62E8DE05', 'issuer_id': 'http://mock-idp', 'uid': 'frodo', 'homeorganization': 'example.com'}
Nov 05 08:58:47 app1-tf1 gunicorn[1110490]: DEBUG:user_api:user: eduteams, mfa_idp_allowed: False (entity_id_allowed=[], schac_home_allowed=[], entity_id=http://mock-idp, schac_home=example.com
Nov 05 08:58:47 app1-tf1 gunicorn[1110490]: DEBUG:user_api:user: eduteams, Returning interrupt for user d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org from issuer http://mock-idp to perform 2fa
Nov 05 08:58:47 app1-tf1 gunicorn[1110490]: INFO:base:user: eduteams, Path /api/users/proxy_authz POST {"user_id": "d5554f7639d5b1357e75668d363e066312812353@acc.sram.eduteams.org", "user_email": "frodo@example.com", "service_id": "APP-18DE6298-7BDD-4CFA-9399-E1CC62E8DE05", "issuer_id": "http://mock-idp", "uid": "frodo", "homeorganization": "example.com"}
```

**Comment by oharsta** [comment] 2024-11-05 13:27
Proposed solution: leave it as it is now and configure the MFA session timeout relatively small. This way the user is automatically authorised when - after the MFA is confirmed - eduTeams calls `authz_proxy` for the second time after the redirect to `continue_url`. Because the MFA session timeout is relatively short, the user will be redirected to the /interrupt page when login with other devices. Alternative is to change the implementation in eduTeams.

**Comment by oharsta** [comment] 2024-11-08 10:37
Assigned to Bas to make the final verdict.

**Closed** 2024-11-08 10:38 UTC
