### ISSUE TITLE
SQL integrity error in collaboration_memberships

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1127] opened 2023-12-11 13:25 UTC
In prod, I see a number of these errors:

```
Traceback (most recent call last):
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry '1143-961' for key 'unique_members'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 191, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/invitation.py", line 241, in invitations_accept
    groups = invitation.groups + list(filter(lambda ag: ag.auto_provision_members, collaboration.groups))
  File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
    return object.__getattribute__(self, name)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1083, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1118, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 966, in _load_for_state
    return self._emit_lazyload(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 1129, in _emit_lazyload
    result = session.execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2120, in _execute_internal
    ) = compile_state_cls.orm_pre_session_exec(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 543, in orm_pre_session_exec
    session._autoflush()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2923, in _autoflush
    raise e.with_traceback(sys.exc_info()[2])
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2912, in _autoflush
    self.flush()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4299, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb.IntegrityError) (1062, "Duplicate entry '1143-961' for key 'unique_members'")
[SQL: INSERT INTO collaboration_memberships (`role`, status, expiry_date, user_id, invitation_id, collaboration_id, created_by, updated_by) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('member', 'active', None, 1143, None, 961, 'xxx@sram.surf.nl', 'xxx@sram.surf.nl')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**Comment by oharsta** [comment] 2023-12-22 15:06
Hopefully fixed in https://github.com/SURFscz/SBS/commit/017179c8a46d104016cf89c358301900d3026201. Could not reproduce in integration test. @baszoetekouw Can you check for occurrences of the error message once this commit https://github.com/SURFscz/SBS/commit/017179c8a46d104016cf89c358301900d3026201 is on prod?

**Closed by oharsta** 2023-12-22 15:06 UTC
Labels: bug
