### ISSUE TITLE
When creating or requesting a CO, pre-fill a random default image from the gallery for the logo

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1262] opened 2024-02-23 09:32 UTC

**Comment by oharsta** [comment] 2024-09-06 12:17
Rephrase to refactor entire pick-image modal

**Comment by FlorisFokkinga** [comment] 2024-09-06 12:22
Duplicate of
- #896

**Comment by logan-life** [comment] 2024-09-09 10:35
Close as duplicate

**Comment by logan-life** [comment] 2024-09-09 10:36
Duplicate of #896

**Closed by logan-life** 2024-09-09 10:36 UTC
Labels: UI
