### ISSUE TITLE
Unit manager cannot create a CO when they are also admin of a different organisation

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1129] opened 2023-12-14 09:00 UTC
![image](https://github.com/SURFscz/SBS/assets/80269262/9314665b-be48-499d-8e78-a01d8c03531c)

**Comment by oharsta** [comment] 2023-12-14 17:49
@FlorisFokkinga Please add the scenario to reproduce.

**Comment by oharsta** [comment] 2023-12-20 14:22
https://test.sram.surf.nl/organisations/300/admins, 
Impersonate user 'SRAM demo' in user overview for supper admin.

**Comment by oharsta** [comment] 2023-12-21 13:35
Duplicate of https://github.com/SURFscz/SBS/issues/1142

**Closed by oharsta** 2023-12-21 13:35 UTC
Labels: bug, UI

**Comment by FlorisFokkinga** [comment] 2023-12-22 09:25
Reproduction scenario is fixed.
